# Use an official Python runtime as a parent image
FROM python:3

# Set the working directory inside the container
WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .env .
# Copy your Python script into the container
COPY csv_loader.py .


# Run your Python script
CMD ["python", "csv_loader.py"]
