version: '3.8'

services:
  backend:
    container_name: volteras_services_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
  db:
    container_name: volteras_services_db
    image: postgres:11
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  csv_loader:
    container_name: volteras_services_csv_loader
    build:
      context: .
      dockerfile: Dockerfile-csv
    env_file:
      - .env
    volumes:
      - ./csv_loader.py:/csv_loader.py
      - ./database/csv:/database/csv  # Mount the CSV folder
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_PWD}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
